config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  resources :trades, only: %i[show index]
  resources :users, only: %i[index show] do
    resources :messages, only: %i[create]
  end
  get 'profiles/my_dashboard'
  get 'profiles/upload_csv'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/conversation.rb
class Conversation < ApplicationRecord
  has_many :messages, dependent: :destroy
  belongs_to :user1, class_name: "User"
  belongs_to :user2, class_name: "User"

  scope :between, -> (user1, user2) do
    where("(conversations.user1_id = :user1_id AND conversations.user2_id = :user2_id)
        OR (conversations.user1_id = :user2_id AND conversations.user2_id = :user1_id)",
            { user1_id: user1.id, user2_id: user2.id })
  end

  def other_user(user)
    if user1 == user
      user2
    elsif user2 == user
      user1
    else
      nil
    end
  end
end

app/models/currency.rb
class Currency < ApplicationRecord
  has_many :user_currencies, dependent: :destroy
  has_many :start_currencies_trades, class_name: "Trade", foreign_key: :start_currency_id, dependent: :destroy
  has_many :end_currencies_trades, class_name: "Trade", foreign_key: :end_currency_id, dependent: :destroy

  validates :name, presence: true
  validates :is_crypto, inclusion: [true, false]
  validates :description, presence: true
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :conversation
  validates :content, presence: true
end

app/models/trade.rb
class Trade < ApplicationRecord
  belongs_to :user
  belongs_to :start_currency, class_name: "Currency"
  belongs_to :end_currency, class_name: "Currency"

  validates :date, presence: true
  validates :type_of_trade, presence: true, inclusion: { in: %w[buy sell] }
  validates :price, presence: true, numericality: { greater_than_or_equal_to: 0 }
  validates :volume, presence: true, numericality: { greater_than_or_equal_to: 0 }
  validates :income_tax, presence: true
  validates :tax_rate, presence: true, numericality: { greater_than_or_equal_to: 0, less_than: 1.0 }
  validates :total_value, presence: true
  validates :amount_tax_free, presence: true

  after_create :calculate_user_score

  private

  def calculate_user_score
    user.calculate_score
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :conversations_as_user1, class_name: "Conversation", foreign_key: :user1_id, dependent: :destroy
  has_many :conversations_as_user2, class_name: "Conversation", foreign_key: :user2_id, dependent: :destroy
  has_many :messages, dependent: :destroy
  has_many :trades, dependent: :destroy
  has_many :user_currencies, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :photo

  validates :username, presence: true, uniqueness: true
  validates :first_name, presence: true
  validates :last_name, presence: true

  def calculate_score
    Trade.where(user: self).sum do
      rand(30..49)
    end
  end

  def last_messages(count = 100)
    Message.joins(:conversation)
           .where("conversations.user1_id  =  :user1_id OR conversations.user2_id = :user1_id", user1_id: id)
           .order(created_at: :desc)
           .limit(count)
  end

  def last_chat_partners(count = 4)
    users = []
    last_messages.each do |message|
      user = message.conversation.other_user(self)
      users << user unless users.include?(user) || user.nil?
    end
    return users.first(count)
  end
end

app/models/user_currency.rb
class UserCurrency < ApplicationRecord
  belongs_to :user
  belongs_to :currency

  validates :amount, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[username photo ledger_address bio first_name last_name])
    devise_parameter_sanitizer.permit(:account_update, keys: %i[username photo ledger_address bio first_name last_name])
  end

  def default_url_options
    { host: ENV["DOMAIN"] || "localhost:3000" }
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action do
    @user = User.find(params[:user_id])
    @conversation = helpers.find_or_create_conversation(current_user, @user)
  end

  def create
    @message = @conversation.messages.new(message_params)
    @message.user = current_user
    @message.save
    ConversationChannel.broadcast_to(
      @conversation,
      render_to_string(partial: "message", locals: { message: @message })
    )
  end

  private

  def message_params
    params.require(:message).permit(:content)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]
  def home
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  # const DATA_COUNT = 5
  # const NUMBER_CFG = { count: DATA_COUNT, min: 0, max: 100 }

  def my_dashboard
    @trades = current_user.trades.order(created_at: :desc)
    colors = ["#003F5C", "#EC6B56", "#64C2A6", "#58508D", "#FFA600", "#2D87BB", "#BC5090", "#FFC154", "#FF6361", "#E6F69D", "#AADEA7"]
    labels = current_user.user_currencies.map do |uc|
      uc.currency.name
    end
    datas = current_user.user_currencies.map do |uc|
      (uc.amount * uc.currency.current_euro_value).round(2)
    end
    @total = 0
    @total = current_user.user_currencies.map do |uc|
      @total += (uc.amount * uc.currency.current_euro_value).round(2)
    end
    @chart_data = {
      labels: labels,
      datasets: [{
        label: 'My First dataset',
        backgroundColor: colors,
        borderColor: '#878B93',
        data: datas
      }]
    }
    # @chart_options = {
    #   type: 'pie',
    #   data: data,
    # }
    @chart_options = {
      options: {
        responsive: false,
        plugins: {
          legend: {
            position: 'top',
            fullSize: false
          },
          title: {
            display: true,
            text: 'Chart.js Pie Chart'
          }
        }
      }
    }
    @displayed_users = current_user.last_chat_partners
  end

  def upload_csv
    @new_trades = current_user.trades.new
  end
end

app/controllers/trades_controller.rb
class TradesController < ApplicationController
  def index
    @trades = Trade.where(user: current_user).order(date: :desc)
  end

  def show
    @trade = Trade.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @gold_users = User.where("score > ?", 400).order(score: :desc)
    @silver_users = User.where("? < score AND score < ?", 200, 400).order(score: :desc)
    @bronze_users = User.where("score < ?", 200).order(score: :desc)
  end

  def show
    @user = User.find(params[:id])
    setup_video_call_token
    @conversation = helpers.find_or_create_conversation(current_user, @user)
    @message = Message.new
    if @conversation.present?
      @messages = @conversation.messages
    else
      @messages = []
    end
  end

  private

  def setup_video_call_token
    # No chatting with yourself
    return if @user == current_user

    twilio = TwilioService.new
    twilio.generate_token(current_user, @user)
    @twilio_jwt = twilio.jwt
    @room_id = twilio.room_id
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/conversation_helper.rb
module ConversationHelper
  def find_or_create_conversation(user1, user2)
    conversation = Conversation.between(user1, user2).first
    if conversation.nil?
      conversation = Conversation.create(user1: user1, user2: user2)
    end
    conversation
  end
end

app/helpers/meta_tags_helper.rb
module MetaTagsHelper
  def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META["meta_title"]
  end

  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META["meta_description"]
  end

  def meta_image
    meta_image = (content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META["meta_image"])
    # little twist to make it work equally with an asset or a url
    meta_image.starts_with?("http") ? meta_image : image_url(meta_image)
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= meta_title %></title>
    <meta name="description" content="<%= meta_description %>">

    <!-- Facebook Open Graph data -->
    <meta property="og:title" content="<%= meta_title %>" />
    <meta property="og:type" content="website" />
    <meta property="og:url" content="<%= request.original_url %>" />
    <meta property="og:image" content="<%= meta_image %>" />
    <meta property="og:description" content="<%= meta_description %>" />
    <meta property="og:site_name" content="<%= meta_title %>" />

    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= favicon_link_tag 'favicon.ico' %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
  <div class="page-container">
    <div class="navbar-container"><%= render "shared/navbar" %></div>
    <%= render 'shared/flashes' %>
    <div class="content-container"><%= yield %></div>
    <div class="footer-container"><%= render "shared/footer" %></div>
  </div>

  </body>
</html>

app/views/messages/_message.html.erb
<div class="message" id="message-<%= message.id %>">
  <small>
  <strong> <%= message.user.username%> </strong>
    <i> <%= message.created_at.strftime("%a %b %e at %l:%M %p") %> </i>
  </small>
  <p> <%= message.content %> </p>
</div>

app/views/pages/home.html.erb
<div class="container home-animation">
  <main>
    <header>
      <h2 class="subheader">— Crypto4You</h2>
      <h1>Organize and structure your crypto investments</h1>
      <p>A simple and effective way to highlight your crypto investments.
        We help you to have more transparency over your taxes and to simply store your trades in a convenient way to get a great review over your trades and taxes. </p>
    </header>

    <img src="https://images.unsplash.com/photo-1558459654-c430be5b0a44?crop=entropy&cs=tinysrgb&fit=crop&fm=jpg&ixid=MXwxNDU4OXwwfDF8cmFuZG9tfHx8fHx8fHw&ixlib=rb-1.2.1&q=80&w=960&h=500" alt="" />
    <section>
    </section>
    <div class="callout">
   <%= image_tag "portfolio.png", alt: "", width: 2000 %>
  </main>
</div>

app/views/profiles/my_dashboard.html.erb
<div class="content-dashboard">
  <br>
  <br>
  <br>
    <div class="dashboard-left">
      <h2 > Hi <%= current_user.username %>, welcome back!</h2>
      <div class="dashboard-left-overview-charts">
        <div class="dashboard-left-overview">
          <h3 class="text-center">Your Assets</h3>
          <div class="text-center">
           <h6>Total worth Portfolio: <%= number_to_currency(@total.sum.round(2), unit: "€", format: "%n %u") %></h6>
          </div>
          <ul>
            <hr>
            <% current_user.user_currencies.each do |uc| %>
            <li> <%= uc.currency.name %> | Price: <%= number_to_currency(uc.currency.current_euro_value.round(2), unit: "€", format: "%n %u") %> |
            <br>
            Volume: <%= uc.amount %>  | Value: <% value = uc.currency.current_euro_value.round(2) * uc.amount.round %> <%= number_to_currency(value.round(2), :unit => "€", format: "%n %u") %> </li>
            <hr>
            <%end  %>
          </ul>
        </div>
        <div class="dashboard-left-chart">
          <div class="card-header-date">
            <h3 class="text-center">Portfolio Mix</h3>
            <h6 class="text-center"><%= Date.current%></h6>
          </div>
          <div class="card-chart"
                style="position: relative; height: 60vh; width: 45vw"
                data-controller="chart"
                data-chart-data-value="<%= @chart_data.to_json %>"
                data-chart-type-value="pie"
                data-chart-options-value="<%= @chart_options.to_json %>"
                >
            <canvas
             data-chart-target="canvas"></canvas>
          </div>
        </div>
      </div>
      <div class="dashboard-left-csv-trades">
        <div class="csv-upload">
          <%= link_to "Upload File", profiles_upload_csv_path, class: "btn btn-success" %>
        </div>
        <div class="trades-and-taxes">
          <%= link_to "Your Trades and Taxes", trades_path, class: "btn btn-success" %>
        </div>
      </div>
    </div>
    <div class="dashboard-right-profile">
      <div class="card-profile">
        <div class="card-profile-head">
          <%= cl_image_tag current_user.photo.key, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <%= current_user.username %>
          <hr>
        </div>
        <div class="container recent-users">
          Recent User-Interaction:
          <ul>
            <% @displayed_users.each do |user|%>
              <hr>
                <li> <%= cl_image_tag user.photo.key, class: "avatar-small" %> <%= link_to user.username, user_path(user) %> </li>
            <% end  %>
            <hr>
          </ul>
        </div>
        <div class="text-center">
        <%= link_to "Show Leaderboard", users_path(:id), class: "btn btn-success" %>
        </div>
      </div>
    </div>
</div>

app/views/profiles/upload_csv.html.erb
<%= link_to profiles_my_dashboard_path(current_user) do  %>
  <i class="fas fa-arrow-circle-left arrow-upload-page"></i>
<% end %>
<div class="container upload-container">
  <h1>Upload your CSV file</h1>
  <div class="upload-card">
  <h1>Upload your CSV file</h1>
    <%= form_with do |form| %>
      <%= form.file_field :trades %>
      <%= form.submit %>
    <% end %>
  </div>
</div>

<%# , value: <i class="fas fa-plus"></i> %>
<%# label: <i class="fas fa-plus-square"></i> %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="github.com"><i class="fab fa-github"></i></a>
    <a href="instagram.com"><i class="fab fa-instagram"></i></a>
    <a href="facebook.com"><i class="fab fa-facebook"></i></a>
    <a href="twitter.com"><i class="fab fa-twitter"></i></a>
    <a href="linkedin.com"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    © 2021 Crypto4you by Sebastian Burkhardt, Luis Kohl, Marcus von Wrede und Finn Erdmann
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "LogoMakr-8umXMq.jpg" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "My Dashboard", profiles_my_dashboard_path, class: "nav-link" %>
          </li>
          <li class="nav-item active">
            <%= link_to "Leaderboard", users_path, class: "nav-link" %>
          </li>
          <li class="nav-item active">
            <%= link_to "Upload CSV", profiles_upload_csv_path, class: "nav-link" %>
          </li>
          <li class="nav-item active">
            <%= link_to "Display Trades", trades_path, class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <%= cl_image_tag current_user.photo.key, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Edit Profile",  edit_user_registration_path, class: "dropdown-item" %>
              <%= link_to "My Dashboard",  profiles_my_dashboard_path, class: "dropdown-item" %>
              <%= link_to "Leaderboard", users_path, class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Sign up", new_user_registration_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/trades/index.html.erb
<div class="container index-container">
  <h1 class="mb-5">Trades and Taxes</h1>
  <%= link_to profiles_my_dashboard_path(current_user), class:"btn-back" do  %>
  <i class="fas fa-arrow-circle-left arrow"></i>
  <% end %>
  <div class="d-flex justify-content-center">
      <table>
        <thead>
          <tr>
            <th>📆 Date</th>
            <th> Ordertype </th>
            <th> Currency </th>
            <th>Price</th>
            <th>Volume</th>
            <th>Total Value</th>
            <th>Amount taxes due</th>
          </tr>
        </thead>
        <tbody>
          <% @trades.each do |trade| %>
            <tr>
              <td><%= trade.date %></td>
              <td><%= trade.type_of_trade %></td>
              <td> <% if trade.type_of_trade == 'buy' %>
                      <img src="<%= trade.end_currency.logo_url %>" alt="<%=trade.end_currency.symbol %>">
                      - <%= trade.end_currency.name %>
                    <% elsif trade.type_of_trade == 'sell' %>
                      <img src="<%= trade.start_currency.logo_url %>" alt="<%=trade.start_currency.symbol %>">
                      - <%=trade.start_currency.name %>
                    <% end %> </td>
              <td><strong>
                <%= number_to_currency(trade.price.round(2), unit: "€", format: "%n %u") %>
              </strong></td>
              <td><strong><%= trade.volume %>  </strong>
                          <% if trade.type_of_trade == 'buy' %>
                            <%=trade.end_currency.symbol %>
                          <% elsif trade.type_of_trade == 'sell' %>
                            <%=trade.start_currency.symbol %>
                          <% end %> </td>
              <td><strong><%= number_to_currency(trade.total_value, unit: "€", format: "%n %u") %> </strong></td>
              <td><strong><%= number_to_currency(trade.income_tax, unit: "€", format: "%n %u") %> </strong></td>
            </tr>
          <% end %>
        </tbody>
      </table>
  </div>
</div>

app/views/trades/show.html.erb
<div class="container">
    <h1> Your details on the trade from</h1> <%= @trade.date %>
  <div class="receipt text-center">
  </div>
</div>

app/views/users/_chat.html.erb
<div data-controller="conversation-subscription", data-conversation-subscription-conversation-id-value="<%= @conversation.id %>">
  <div class="card chat-card">
    <div class="messages" data-conversation-subscription-target="messages">
      <% if @messages.any? %>
        <% @messages.each do |message|%>
          <%= render "messages/message", message: message %>
        <%end %>
      <%end %>
    </div>
  </div>
  <%= simple_form_for [@user, @message] do |f| %>
    <%= f.input :content, as: :string, label: false, input_html: { 'data-conversation-subscription-target': 'input' } %>
  <% end %>
</div>

app/views/users/_video.htm.erb
<div class="video-call"
      data-controller="video-call"
      data-video-call-access-token-value="<%= twilio_token %>"
      data-video-call-room-id-value="<%= room_id %>"
      data-video-call-buddy-video-width-value="200"
      >
  <div class="call-video-views">
    <div id="remote-video" data-video-call-target="buddyVideo">
      <div class="no-call" data-video-call-target="noCall">
        No call in progress. Click 'Call' to connect!
      </div>
      <div class="waiting-for-buddy d-none"
            data-video-call-target="awaitingBuddy">
        Waiting for <%= @user.name %> to join...
      </div>
    </div>
    <div id="local-video" data-video-call-target="localVideo"></div>
  </div>
  <div class="call-buttons">
    <%= link_to '#',
                class: 'call-button btn-start-call',
                data: {
                  action: 'click->video-call#joinCall',
                  video_call_target: 'joinCallButton'
                } do %>
      <i class="fas fa-phone"></i> Call
    <% end %>
    <%= link_to '#',
                class: 'call-button btn-end-call d-none',
                data: {
                  action: 'click->video-call#endCall',
                  video_call_target: 'endCallButton'
                } do %>
      <i class="fas fa-phone-slash"></i> End
    <% end %>
  </div>
</div>

app/views/users/_video.html.erb
<div class="modal fade" id="videoModal" tabindex="-1" role="dialog" aria-labelledby="videoModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered modal-fullscreen" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLongTitle"><%= @user.username %></h5>
        <button type="button" class="btn btn-secondary" data-bs-toggle="modal" aria-label="Close">
          <span aria-hidden="true"> <i class="fas fa-times"></i> </span>
        </button>
      </div>
      <div class="modal-body">
        <div class="video-call"
          data-controller="video-call"
          data-video-call-access-token-value="<%= @twilio_jwt %>"
          data-video-call-room-id-value="<%= @room_id %>"
          data-video-call-buddy-video-width-value="200"
        >
        <div class="call-video-views">
          <div id="remote-video" data-video-call-target="buddyVideo">
            <div class="no-call" data-video-call-target="noCall">
              Press 'Call' to speak with <strong> <%= @user.username %> </strong>
            </div>
            <div class="waiting-for-buddy d-none"
                  data-video-call-target="awaitingBuddy">
              Waiting for <%= @user.username %> to join...
            </div>
          </div>
          <div id="local-video" data-video-call-target="localVideo"></div>
        </div>
        <div class="call-buttons">
          <%= link_to '#',
                      class: 'call-button btn-start-call btn btn-success',
                      data: {
                        action: 'click->video-call#joinCall',
                        video_call_target: 'joinCallButton'
                      } do %>
            Call <i class="fas fa-video"></i>
          <% end %>
          <%= link_to '#',
                      class: 'call-button btn-end-call d-none',
                      data: {
                        action: 'click->video-call#endCall',
                        video_call_target: 'endCallButton',
                        'bs-toggle': 'modal'
                      } do %>
            End <i class="fas fa-video-slash"></i>
          <% end %>
        </div>
      </div>
      </div>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<%= link_to profiles_my_dashboard_path(current_user), class:"btn-back lower" do  %>
  <i class="fas fa-arrow-circle-left arrow-leaderboard"></i>
<% end %>
<h1 class="text-center">Crypto4you Leaderboard</h1>
<div class="container">
  <h2 class="text-center">Gold status <i class="fas fa-medal gold"></i></h2>
  <% @gold_users.each do |user| %>
    <div class="user">
      <strong> <%= cl_image_tag user.photo.key, class: "avatar-small" %> <%= link_to user.username, user_path(user) %> </strong> ⭐️Score: <%= user.score %> <p> "<%= user.bio %>" </p>
    </div>
  <% end %>
  <h2 class="text-center">Silver status <i class="fas fa-medal silver"></i></h2>
  <% @silver_users.each do |user| %>
    <div class="user">
      <strong> <%= cl_image_tag user.photo.key, class: "avatar-small" %> <%= link_to user.username, user_path(user) %> </strong> ⭐️Score: <%= user.score %> <p> "<%= user.bio %>" </p>
    </div>
  <% end %>
  <h2 class="text-center">Bronze status <i class="fas fa-medal bronze"></i></h2>
  <% @bronze_users.each do |user| %>
    <div class="user">
      <strong> <%= cl_image_tag user.photo.key, class: "avatar-small" %> <%= link_to user.username, user_path(user) %> </strong> ⭐️Score: <%= user.score %> <p> "<%= user.bio %>" </p>
    </div>
  <% end %>
  <br>
</div>

app/views/users/show.html.erb
<%= link_to profiles_my_dashboard_path(current_user), class:"btn-back higher" do  %>
  <i class="fas fa-arrow-circle-left arrow-chat"></i>
<% end %>
<div class="container">
  <br>
  <h2 class="text-center"> <%= @user.username %> </h2>
  <div class="card">
    <div class="container">
      <%= cl_image_tag @user.photo.key, class: "avatar-medium" %>
      <strong> ⭐️ Score: <%= @user.score %></strong> <small>Ledger: <%= @user.ledger_address %></small>
      <br>
      <%= @user.bio %>
    </div>
  </div>
  <br>
  <br>
  <% if @user != current_user %>
    <div class="chat-header">
      <h4>Your chat </h4>
      <button type="button" class="btn btn-success btn-start-call" data-bs-toggle="modal" data-bs-target="#videoModal">
        Start your call now  <i class="fas fa-video"></i>
      </button>
    </div>
    <%= render 'users/chat' %>
    <%= render 'users/video' %>
  <% else %>
    <h4>Look at your beautiful page</h4>
    <div class="card">
    </div>
  <% end %>
  <%= link_to "Back to dashboard", profiles_my_dashboard_path(current_user), class: "btn btn-secondary center" %>
</div>